### ISSUE TITLE
Dependency conflict with flutter_test

### ISSUE THREAD

**Issue by brizaldi** [dart-lang/intl_translation#100]
`Because every version of flutter_test from sdk depends on petitparser 2.4.0 and intl_translation >=0.17.10 depends on petitparser ^3.0.0, flutter_test from sdk is incompatible with intl_translation >=0.17.10`

**Comment by boskokg** [comment]
I think this error is fixed on flutter stable and dev channel.

**Comment by brizaldi** [comment]
still got the same error after upgrading to beta channel

**Comment by lzhuor** [comment]
@boskokg May I know which version are you on?

**Comment by boskokg** [comment]
@lzhuor I removed it from the project. I when to simpler approach...

**Comment by lzhuor** [comment]
@boskokg Got it. I found that using `intl_translation: ^0.17.8` works fine. (one patch lower)

**Comment by lzhuor** [comment]
@boskokg May I ask if simple approach support interoperation (args) out-of-the-box?

**Comment by brizaldi** [comment]
> 
> 
> @boskokg May I know which version are you on?

Flutter Channel beta, v1.17.0-3.2.pre

**Comment by awhitford** [comment]
I am able to use `intl_translation: ^0.17.9`, however I am unable to upgrade to `0.17.10` because:

> Because intl_translation >=0.17.10 depends on petitparser ^3.0.0 and every version of flutter_test from sdk depends on petitparser 2.4.0, intl_translation >=0.17.10 is incompatible with flutter_test from sdk.

Note that I still have this problem after upgrading to **Flutter 1.17.0**.

**Comment by awhitford** [comment]
It looks like [`flutter_test` removed `petitparser` as a dependency](https://github.com/flutter/flutter/commit/efdce3cf728c96d47e216120512595e8d9a3022b#diff-6db519d06b539bb165a44ad589217e9e) on April 9, 2020.  However, that did not make it into the Flutter 1.17.0 release.  It looks like we may need to wait until Flutter 1.18.0.

**Comment by 0biWanKenobi** [comment]
@awhitford  that... sucks

**Comment by princeteck** [comment]
@davidmorgan when can we expect this fix or next version of the package ?

as much as I am reading, the latest version of `flutter_test` is not depended on `petitparser`...

stuck with below error:
```
Because every version of flutter_test from sdk depends on petitparser 2.4.0 and intl_translation >=0.17.10 depends on petitparser ^3.0.0, flutter_test from sdk is incompatible with intl_translation >=0.17.10.
So, because app depends on both intl_translation ^0.17.10 and flutter_test any from sdk, version solving failed.

pub get failed (1; So, because app depends on both intl_translation ^0.17.10 and flutter_test any from sdk, version solving failed.)
exit code 1
```

**Comment by davidmorgan** [comment]
That needs fixing with a release of flutter_test, not here.

**Comment by maheshmnj** [comment]
> @boskokg Got it. I found that using `intl_translation: ^0.17.8` works fine. (one patch lower)


thanks this worked on the latest stable channel  v1.17.5

**Comment by yourshinsuke** [comment]
@maheshmnj
really?

**Comment by maheshmnj** [comment]
@yourshinsuke  yes ofcourse it did work for me

**Comment by yourshinsuke** [comment]
@maheshmnj 
Thank you.
OK.
I removed `test: ^1.14.5` in `pubspec.yaml` and it can pub get.

**Comment by awhitford** [comment]
**Flutter 1.20.0** was released today.  You will then be able to use version **0.17.10**.

**Comment by ArkadiuszDatka** [comment]
I had a similar problem with flutter_test and test. I solved it by downgrading test version to ^ 0.14.4 :)

`The current Dart SDK version is 2.8.4.

Because test >=1.16.0-nullsafety requires SDK version >=2.10.0-0 <2.10.0 and test >=1.14.5 <1.15.0 depends on test_api 0.2.16, test >=1.14.5 <1.15.0-∞ or >=1.16.0-nullsafety requires test_api 0.2.16.
And because test >=1.15.0 <1.15.3 depends on test_api 0.2.17, test >=1.14.5 <1.15.3-∞ or >=1.16.0-nullsafety requires test_api 0.2.16 or 0.2.17.
And because test >=1.15.3 <1.16.0-nullsafety depends on test_api 0.2.18 and every version of flutter_test from sdk depends on test_api 0.2.15, flutter_test from sdk is incompatible with test >=1.14.5.
So, because flutter_tests_app depends on both flutter_test any from sdk and test ^1.14.5, version solving failed.
pub get failed (1; So, because flutter_tests_app depends on both flutter_test any from sdk and test ^1.14.5, version solving failed.)
Process finished with exit code 1`

**Comment by shinriyo** [comment]
```
Because every version of flutter_test from sdk depends on collection 1.15.0-nullsafety.2 and dartx >=0.2.0 <0.5.0 depends on collection >=1.14.11 <1.15.0, flutter_test from sdk is incompatible with dartx >=0.2.0 <0.5.0.
So, because andu depends on both dartx ^0.4.1 and flutter_test any from sdk, version solving failed.
```

same issue.

beta only??

Flutter 1.22.0-9.0.pre • channel dev • https://github.com/flutter/flutter.git Framework • revision 7a43175198 (7 days ago) • 2020-08-28 23:18:04 -0400 Engine • revision 07e2520d5d Tools • Dart 2.10.0 (build 2.10.0-73.0.dev)

**Comment by mosuem** [comment]
Fixed, as the dependency is removed.
