### ISSUE TITLE
analyzer 0.40.x support

### ISSUE THREAD

**Issue by proninyaroslav** [dart-lang/intl_translation#114]
@davidmorgan 
Many projects have switched to support `analyzer 0.40.x`, for this reason I can't use new versions of packages, because `intl_translation` is limited only by version `0.39.x`

**Comment by davidmorgan** [comment]
If `analyzer` is a dev dependency then `dependency_overrides` should unblock you, i.e. add `analyzer` under `dependency_overrides` with a `0.40` version.

**Comment by proninyaroslav** [comment]
@davidmorgan 
Thank you, it works.
