### ISSUE TITLE
Localization generation(generate_from_arb) does not properly generate interpolated variable names that start with underscore(_)

### ISSUE THREAD

**Issue by rvaleev** [dart-lang/intl_translation#119]
Angular has in some places interpolated variables that start with underscore(_). For example, here: https://github.com/dart-lang/angular_components/blob/master/angular_components/lib/material_input/material_number_validators.dart#L99

During generation intl_translation library does not generate properly dart code so that `Enter a number $_lowerBound or greater` results into  `static m10(_lowerBound) => "Enter a number {_lowerBound} or greater";` which is not valid.

It should generate `static m10(_lowerBound) => "Enter a number ${_lowerBound} or greater";`

**Comment by mosuem** [comment]
Closing in favor of #127.
