### ISSUE TITLE
extract_to_arb not working when used as a filter.

### ISSUE THREAD

**Issue by abhishek-buragadda** [dart-lang/intl_translation#12]
I am writing a custom pipe which takes the string as input (along with other args )and return the Intl.message() . When i run extract_to_arb i am getting an empty arb file. Following is the usage of the pipe .
```
@Pipe("testPipe")
class TestPipe extends PipeTransform{
    transform(String input,String name,  args , String desc){
        return  Intl.message(input,
            name: name,
            args: args,
            desc : desc
        );
    }

}
```
`<h2>{{"Hello" | testPipe:test:[]: this is test}}</h2>`

My arb file 

`{}`

 pubspec.yaml:

> dependencies :
>     angular: ^4.0.0-alpha
>     angular_components: ^0.6.0-alpha+2
>     intl: 0.14.0
> dev-dependencies:
>      intl_translation: any

**Comment by BorisNaguet** [comment]
Hello,
from what I understand, it's not related to using it specifically in a pipe, but what you want to do can't be achieved if you want to use extract_to_arb.

 This command needs to have `input`, `name` and `args` _hardcoded_ in the `Int.message` call.
Also, it must be called in a function whose args match the args list like in example:

```dart
	String continueMessage() => Intl.message(
		"Hit any key to continue",
		name: "continueMessage",
		args: [],
		desc: "Explains that we will not proceed further until "
			"the user presses a key");

	String greetingMessage(name) => Intl.message(
		"Hello $name!",
		name: "greetingMessage",
		args: [name],
		desc: "Greet the user as they first open the application",
		examples: const {'name': "Emily"});
```

**Comment by alan-knight** [comment]
Yes, extract_to_arb is not particularly smart. It knows how to work on Dart code with literal values for the parameters to the Intl message. It doesn't know anything about values in html or about Angular processing.

It would be possible to write something that knows how to read Angular html files and extract text from them into an ARB file, but as far as I know, that doesn't exist right now. Invoking the message might be able to look something like your pipe example, but I don't know enough Angular to be sure.
