### ISSUE TITLE
Add support to Flutter Web

### ISSUE THREAD

**Issue by kazenskiw3o** [dart-lang/intl_translation#121]
Currently I'm working on a project which required localization for both mobile and web 
I've developed the mobile version using this plugin, and now i have to make the web version as well
If i have to use different plugin, there will be too much work to do, and I have a tight deadline
So, can you please make this plugin works on flutter web?

**Comment by mosuem** [comment]
I believe the [Flutter localization workflow](https://docs.flutter.dev/development/accessibility-and-localization/internationalization) should also work on web.
