### ISSUE TITLE
How is this package maintaned? It seems to not merge any open PRs fixing stuff

### ISSUE THREAD

**Issue by nstrelow** [dart-lang/intl_translation#124]
I am just complaining, sorry for that.

Anything that can be done to speed things up or approve PRs?
Or is this package dead and will be replaced?

**Comment by aleksakrstic** [comment]
With https://github.com/localizely/intl_utils package we extended `intl_translation` package and continue to maintain it.

The migrations is simple. You just use it with this command:
`flutter pub run intl_utils:generate`

**Comment by mosuem** [comment]
It was a bit neglected, but is now actively maintained again, starting with null safety.
