### ISSUE TITLE
`analyzer` dependency bounds should be bumped to at least `0.40.0`

### ISSUE THREAD

**Issue by MichaelM97** [dart-lang/intl_translation#137]
Due to the release of Flutter 2.0 I've bumped a bunch of dependencies, many of which that use auto-generation now require at least `analyzer 0.40.0`. As this dependency depends on `analyzer 0.39.12` I need to add a depdency override for my dependencies to resolve when using `intl_translation`. However, when attempting to run auto-generation I get the following issue

> Failed to precompile build_runner:build_runner:
> ../../flutter/.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.4.3/lib/src/resolver.dart:454:21: Error: Method not found: 'FeatureSet.fromEnableFlags2'.
>   return FeatureSet.fromEnableFlags2(

**Comment by fvisticot** [comment]
Same issue

**Comment by pinkfish** [comment]
Is anything being updated with this package?  Seems like nothing has happened since August last year?

**Comment by shic** [comment]
Does this lib still under maintenance? If not, please tell us! Thanks a lot!

**Comment by heitor-nsouza** [comment]
Any updates?

**Comment by invlol** [comment]
maybe this could help. 

dependency_overrides:
  analyzer: ">=0.40.0"

inside pubspec.yaml
