### ISSUE TITLE
Access translation by key

### ISSUE THREAD

**Issue by Dominilk** [dart-lang/intl_translation#138]
Hi!

I am in a situation where I get a message-id back from the back-end and I want to implement a translation for each and every message-id I can get back. The most convenient way would be to just add a translation to my .arb file and then just load the corresponding message from it. It'd be very convenient to therefore have a method you can call to get the unformatted message from the file back.

Here is an example of how I'd imagine using it:
```dart
S.of(...).loadRawMessage("<key-value from json>");
```

Thanks!

Edit: Added dart syntax highlighting

**Comment by alan-knight** [comment]
https://github.com/dart-lang/intl/issues/298

**Comment by Dominilk** [comment]
Thanks! How did I overlook that issue
