### ISSUE TITLE
plurals don't work properly

### ISSUE THREAD

**Issue by nt4f04uNd** [dart-lang/intl_translation#141]
`locale` is not counted in generate messages, i.e

```dart
Intl.plural(
    6,
    zero: 'zero',
    one: 'one',
    two: 'two',
    few: 'few',
    many: 'many',
    other: 'other',
    locale: someLocale,
  );
```

after generation becomes that

```dart
Intl.plural(
    6,
    zero: 'zero',
    one: 'one',
    two: 'two',
    few: 'few',
    many: 'many',
    other: 'other',
  );
```

`Intl.plural` can only work properly if you pass `locale`, or override `defaultLocale`, or run `.withLocale()`, neither of which does the generated code and thus the locale goes wrong

**Comment by mosuem** [comment]
What is your use case? The generated code does not need the `locale` parameter, as one class is created for each locale. Please reopen this with more details!
