### ISSUE TITLE
Version solving fails when using newest version of build_runner and/or json_serializable

### ISSUE THREAD

**Issue by kesteinbakk** [dart-lang/intl_translation#145]
Because build_runner >=2.0.0 depends on dart_style ^2.0.0 and intl_translation >=0.17.0 depends on dart_style
  ^1.0.0, build_runner >=2.0.0 is incompatible with intl_translation >=0.17.0.
And because intl_translation <0.17.0 requires SDK version >=1.12.0 <2.0.0, build_runner >=2.0.0 is incompatible
  with intl_translation.
So, because app depends on both intl_translation any and build_runner ^2.0.3, version solving failed.

And:

Because json_serializable >=4.1.0 depends on source_gen ^1.0.0 which depends on dart_style ^2.0.0,
  json_serializable >=4.1.0 requires dart_style ^2.0.0.
And because intl_translation >=0.17.0 depends on dart_style ^1.0.0 and intl_translation <0.17.0 requires SDK
  version >=1.12.0 <2.0.0, json_serializable >=4.1.0 is incompatible with intl_translation.
So, because kra_app_web depends on both intl_translation any and json_serializable ^4.1.2, version solving
  failed.

**Comment by yurijdvornyk** [comment]
Is there any update with this issue?

**Comment by tim-coder** [comment]
ditto
