### ISSUE TITLE
How to escape curly brace in arb file?

### ISSUE THREAD

**Issue by Gerrel** [dart-lang/intl_translation#182]
I'm trying to escape the word {test} in the .arb file.

// dart file
```dart
Intl.message(
        "{test}",
        name: "flutter_test",
        args: []);
```
---
//1. intl_en.arb
```json
{
"flutter_test": "{test}",
  "@flutter_test": {
    "type": "text",
    "placeholders": {},
    "source_text": "{test}"
  },
"@@locale": "en"
}
```
Gives the error:
```
Unhandled exception:
Invalid argument(s)
#0      List.[] (dart:core-patch/growable_array.dart:145:60)
```

---
//2. intl_en.arb
```json
{
  "flutter_test": "\{test\}",
  "@flutter_test": {
    "type": "text",
    "placeholders": {},
    "source_text": "\{test\}"
  },
"@@locale": "en"
}
```
Gives the error:
```
Unhandled exception:
FormatException: Unrecognized string escape (at line 2, character 22)
  "flutter_test": "\{test\}",
                     ^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1392:5)
```
---
//3. intl_en.arb
```json
{
  "flutter_test": "\\{test\\}",
  "@flutter_test": {
    "type": "text",
    "placeholders": {},
    "source_text": "\\{test\\}"
  },
"@@locale": "nl"
}
```
Does not give a error, but shows the result \\{test\\}. ([slash][curly-brace]test[slash][curly-brace])

How to do a proper escape of a curly brace?

**Comment by iulian0512** [comment]
major issue when using with package https://pub.dev/packages/flutter_background_geolocation for android 11 you are required to provide a localized string like this:  "Allow {applicationName}  to access to this device's location in the background?" where application name does not have to be a placeholder.
