### ISSUE TITLE
update intl_* files and add indentation option

### ISSUE THREAD

**Issue by Fandekasp** [dart-lang/intl_translation#20]
What is the best way to update intl_* files ? At first, I ran
```
$ flutter pub pub run intl_translation:extract_to_arb --output-dir=lib/l10n  lib/*
$ for lang in en ja; do cat lib/l10n/intl_messages.arb|jq . > lib/l10n/intl_${lang}.arb; done
```

But afterwards, when adding new translation strings, While I can re-generate the `intl_messages.arb` file, it looks like I need to manually update all the int_*.arb files, a bit painful.
What I'm doing is run `cat lib/l10n/intl_messages.arb|jq .`, then copying the new parts and pasting it in each files. 

Couldn't the script "append" new key/values to each files automatically ? (adding an `--indent=2` option to remove the needs for jq would also be nice).

**Comment by alan-knight** [comment]
It should indent automatically in the next version, there was a pull request for that.

So I guess what you're doing is copying the English version to each language and then manually editing the ARB files? That's not the typical process, usually there's some kind of translation system involved. e.g. upload the extracted messages to Google Translator Toolkit and download the corresponding language files after they've been translated. The translation systems normally take care of of knowing which messages have already been translated.

Right now the extraction program doesn't know anything about what was generated before, and I'm reluctant to complicate it.

It seems like it wouldn't be too hard to to diff the output vs. the previous output and then append all the diff chunks to each translation file. Or use jq (I hadn't seen it before, seems like a handy utility) to get all the message names, diff those, and use jq again to pull out the new ones.

**Comment by Fandekasp** [comment]
Thank you for the reply! 
I didn't know about Google Translator Toolkit, and this sounds like a good process if I can automatize it all.
But I'm wondering about the best practices to convert the arb files to tmx. Blindly trying to convert the arb from json to xml didn't work. I don't even know how the ".arb" extension differ from regular json.
Do you maybe have a link to an example describing the process ?

**Comment by alan-knight** [comment]
I've never used TMX files, where do they enter into it?
I've just uploaded ARB files directly to Google Translator Toolkit https://support.google.com/translatortoolkit/answer/6306383?hl=en&ref_topic=6306365 
or 
https://translate.google.com/toolkit/docupload?hl=en

and in the translation view (when you click on one of the translations) there's a File menu with a Download option, and it automatically gives me ARB. I'm not sure if it's just defaulting to the format in which it was uploaded, or if ARB is the global default.

**Comment by Fandekasp** [comment]
I see, I was in the wrong place in the Translator Toolit, under Translation memories.
Too bad that the Google Translator Toolkit API isn't available anymore :(

Thanks for your help, closing this issue.
