### ISSUE TITLE
"dart migrate" tool flags generated translation files with version 0.18.0 as non-null-safe

### ISSUE THREAD

**Issue by tashiwangdi** [dart-lang/intl_translation#201]
I am working on migrating our codebase to sound null-safety. I managed to update/migrate all plugins in the project to null-safe versions.
Now, when I run dart migrate tool, the tool flags the generated translation files with version 0.18.0 as non-null-safe. From project's pubspec.yaml: 
```
environment:
  sdk: ">=2.7.0 <3.0.0"
```
This is what the dart migrate tool outputs: 

```
[
     1.089s] Analyzing project...
[----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------][    19.906s] Bad state: Error: package has unmigrated dependencies.

Before migrating your package, we recommend ensuring that every library it
imports (either directly or indirectly) has been migrated to null safety, so
that you will be able to run your unit tests in sound null checking mode.  You
are currently importing the following non-null-safe libraries:

  package:my-project/generated/messages_all.dart
  package:my-project/generated/messages_all_locales.dart
  package:my-project/generated/messages_de.dart
  package:my-project/generated/messages_en.dart
  package:my-project/generated/messages_es.dart
  package:my-project/generated/messages_fr.dart
  package:my-project/generated/messages_it.dart

Please upgrade the packages containing these libraries to null safe versions
before continuing.  To see what null safe package versions are available, run
the following command: `dart pub outdated --mode=null-safety`.

To skip this check and try to migrate anyway, re-run with the flag
`--skip-import-check`.
```
If I add a comment - `// @dart=2.12`  in the files mentioned above, then they are not flagged.
Is it a known issue or could someone direct me to something that I  am missing?

**Comment by tashiwangdi** [comment]
If I run dart migrate in the folder that has the generated translation files, it says already migrated:

```
 dart migrate --verbose
[     0.002s] Migrating /my-project/lib/generated
[     0.010s] 
[     0.010s] See https://dart.dev/go/null-safety-migration for a migration guide.
[     0.010s] 
[     0.342s] Analyzing project...
[                                                                                                                                                                                                    ][     0.363s] All sources appear to be already migrated.  Nothing to do.
```

**Comment by tashiwangdi** [comment]
Output for command - `dart pub outdated --mode=null-safety`

```
dart pub outdated --mode=null-safety
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Package Name  Current  Upgradable  Resolvable  Latest  

direct dependencies: all support null safety.

dev_dependencies: all support null safety.
All dependencies opt in to null-safety.
```

**Comment by mosuem** [comment]
Where the messages possibly generated with an older, non null-safe version of `intl_translation`?

**Comment by mosuem** [comment]
Would setting the min sdk to `2.12.0` help?

**Comment by tashiwangdi** [comment]
> Were the messages possibly generated with an older, non null-safe version of `intl_translation`?

The translation files were generated with intl_translation version 0.18.0(null-safe)

**Comment by mosuem** [comment]
Thanks. Does bumping the minimum SDK version help?

**Comment by tashiwangdi** [comment]
> Thanks. Does bumping the minimum SDK version help?

Bumping the min SDK version to 2.12.0 ends up creating lots of analyze error related to null-safety since the project code is not migrated to null-safety yet. I want to use the dart migrate tool interactively to migrate project code rather than doing it by hand :-)

**Comment by tashiwangdi** [comment]
@mosuem :  Is that the way to do it then? Bumping up min SDK version to 2.12.0 and fix all analyze error ?

**Comment by mosuem** [comment]
I am not entirely sure, this is however what Polina seems to recommend in https://medium.com/dartlang/gradual-null-safety-migration-for-large-dart-projects-85acb10b64a9.

**Comment by tashiwangdi** [comment]
> It's odd that the migration tool thinks those files are unmigrated in one context but migrated in another. Is there anything in your project config that calls them out specially? A separate pubspec or analysis options file in `lib/generated`? Or, are the files excluded from analysis somewhere?

Thank you for your suggestion @devoncarew  👍. The generated files were skipped in an analysis options file. Removing the exception resulted in analysis errors saying  `This requires the 'non-nullable' language feature to be enabled`. It's better now.

**Comment by tashiwangdi** [comment]
Thank you @mosuem and @devoncarew for suggestions and being patient with my questions 💯. 
I will close the issue.
