### ISSUE TITLE
ARB not supported anywhere

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/intl_translation#27]
Hi, I' trying to find a way of getting my dart app translated however the file format `arb` doesn't seem to be supported anywhere?

Your readme says "which can be used for input to translation tools like Google Translator Toolkit " however this does not seem the case: "Supported file formats: You can upload translation memories in file format Translation Memory eXchange (TMX) only." [source](https://support.google.com/translatortoolkit/answer/6306382?hl=en)

Services like One Sky App integrate with the [37 file formats](https://www.oneskyapp.com/how-it-works/integrations-plugins/) and arb is not included.

Could you support more file formats to this project to widen support for translation tools and services?

**Comment by alan-knight** [comment]
You want the section above that, which says 

"You can upload documents to translate in any of the following file formats:
... Application Resource Bundle (.arb) ..." (and 12 others)

Lots of those file formats would not be useful for translating a program. It's not very useful to support uploading a Mic

ARB is a convenient file format in that it fully supports the ICU messages semantics, which is what we implement for plurals, gender, etc.  It is not difficult to add formats. The format-specific code is all in extract_to_arb.dart and generate_from_arb.dart, 325 lines of code total, about a third of which is boilerplate command line options and file handling.

The difficulty is if there are semantic mismatches. So, if you upload and download Microsoft Word files there's not a lot we can do. Even if you use a programmatic format like gettext it doesn't support lots of features. Are there particular formats you're interested in?

**Comment by jimmyff** [comment]
sorry, I have no idea what I was seeing the other day but I now see the option to upload arb files. Now I know I can use Translation toolkit arb is perfect for my project.

Thanks

**Comment by jimmyff** [comment]
Google translator toolkit is to be shut down on December 2019.  This means there is will be no solution to my knowledge for maintaining a localised dart project as nobody supports arb files. 

Is there any chance that this package can have a more readily available file format option added in light of GTT shutting down?

**Comment by alan-knight** [comment]
I'm going to consolidate this to #74 
Do you have any suggestions of a format?
