### ISSUE TITLE
intl_translation failed to be analyzed

### ISSUE THREAD

**Issue by ronaldG19** [dart-lang/intl_translation#38]
Because every version of flutter_test from sdk depends on analyzer 0.31.2-alpha.2 and intl_translation >=0.17.0 depends on analyzer ^0.32.1, flutter_test from sdk is incompatible with intl_translation >=0.17.0.
So, because PL depends on both intl_translation ^0.17.0 and flutter_test any from sdk, version solving failed.
pub get failed (1)

: FLUTTER DOCTOR :
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
Process finished with exit code 0

: FLUTTER VERSION :
Already up-to-date.

Upgrading engine...
Already up-to-date.

Flutter 0.5.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision c7ea3ca377 (2 months ago) • 2018-05-29 21:07:33 +0200
Engine • revision 1ed25ca7b7
Tools • Dart 2.0.0-dev.58.0.flutter-f981f09760

**Comment by alan-knight** [comment]
The flutter_test pubspec was updated 17 days ago, so this ought to be fixed with the next flutter release.  In the meantime, you have to either use flutter master, or use an older version of intl_translation
