### ISSUE TITLE
Force Rewrite to Include Name Arg

### ISSUE THREAD

**Issue by timmccall-wf** [dart-lang/intl_translation#51]
Hi!

When calling `rewrite_intl_messages` I need to ensure that `Intl.message` calls always define the `name` argument. Currently, `name` will be added only when the `args` argument exists. I need the `name` to be added regardless of whether `args` exists.

The solution is simple and I can PR a fix if this is something you are willing to accept.

Thanks.

**Comment by alan-knight** [comment]
Sorry, this had gotten filtered down and I didn't notice it. Yes, I'd be happy to accept that as an option. So are you using rewrite_intl_messages on an ongoing basis? Generally I think people have just used it as a way of migrating away from transformer usage.

**Comment by mosuem** [comment]
Closing in favor of #61.
