### ISSUE TITLE
Is this repo abandoned ?

### ISSUE THREAD

**Issue by gedw99** [dart-lang/intl_translation#55]
No updates for a few months but still quite a few holes / gaps.
Currency symbols, etc.

For flutter I need i18n and i10n support.

Please advise..

**Comment by alan-knight** [comment]
No, it's not abandoned. It's also not the right repo for currency symbols, this deals with messages, plurals, genders, etc.  For currency symbols you'd want Intl. What specifically are you looking for in currency symbols? There's a very simple list in there, but there's a tension with this in general between providing useful facilities and not inflating code/data size, as full internationalization support would be approximately the size of ICU.  There's also ongoing work on letting this use ICU (for Flutter) or JS Intl (in browsers) when available.

Both of them are also developed internally to Google and pushed intermittently to github.
