### ISSUE TITLE
Please close merged PRs

### ISSUE THREAD

**Issue by dotdoom** [dart-lang/intl_translation#58]
Some PRs are merged (I guess, internally) or superseded, but not closed. This creates extra cognitive load when looking whether an issue is already worked on.

* https://github.com/dart-lang/intl_translation/pull/14
* https://github.com/dart-lang/intl_translation/pull/15
* https://github.com/dart-lang/intl_translation/pull/16
* https://github.com/dart-lang/intl_translation/pull/17
* https://github.com/dart-lang/intl_translation/pull/18
* https://github.com/dart-lang/intl_translation/pull/29
* https://github.com/dart-lang/intl_translation/pull/48

+cc @alan-knight

**Comment by alan-knight** [comment]
Done. Thanks for pointing those out.
