### ISSUE TITLE
Extract translations from mixins

### ISSUE THREAD

**Issue by ened** [dart-lang/intl_translation#64]
My translation class is getting quite long, and app functionality is intermixed (I have to separate using commas etc).

It would be great if the toolchain would support standard Dart mixins, for example:

```
class MncLocalizations with ExtraLocalizationsMixin {
  static Future<MncLocalizations> load(Locale locale) {
    final String name =
        locale.countryCode.isEmpty ? locale.languageCode : locale.toString();
    final String localeName = Intl.canonicalizedLocale(name);
    return initializeMessages(localeName).then((_) {
      Intl.defaultLocale = localeName;
      return MncLocalizations();
    });
  }
}
```

Should also load the translations from `ExtraLocalizationsMixin`, when running `flutter pub pub run intl_translation:extract_to_arb --output-dir=lib/l10n lib/l10n/mnc_localizations.dart --output-file 'messages.arb'`.

If this already works or better strategies are available, it should probably be documented.

**Comment by ened** [comment]
In the example above, one could obviously run the following:

```
flutter pub pub run intl_translation:extract_to_arb --output-dir=lib/l10n \
  lib/l10n/mnc_localizations.dart \
  lib/l10n/extra_mnc_localizations.dart \
  --output-file 'messages.arb'
```

Which would do exactly as required.

**Comment by alan-knight** [comment]
This should work fine, as mentioned. I don't think the extraction logic should care, or even know, if a message is in a mixin or not. As it seems to work, closing.
