### ISSUE TITLE
How to handle lot of files?

### ISSUE THREAD

**Issue by zreptil** [dart-lang/intl_translation#65]
I have a project that has lots of dart files in it. When running the commands generate_from_arb or extract_to_arb i have to specify each single file in the commandline. When using generate_from_arb i also have to provide every single arb file in the commandline to get a working messages_all.dart file containing every translation.

I call this by using a Windows DOS shell where the commandline is limited to 2047 chars. This limit can easily be exceeded by having a lot of dart files and a project-structure with some directory levels together with many languages. How can this be handled for big projects? Is there a way to use wildcards in the commandline or to call generate_from_arb multiple times without overwriting the results of earlier calls?

**Comment by alan-knight** [comment]
I think wildcards should work, they do on Linux. Inside Google, the corresponding programs for the format we use internally also added an option to read the list from a file. That would be easy to port.

**Comment by zreptil** [comment]
The code doesn't expect wildcards. So i provided a pull request that makes it possible to handle filelists.

**Comment by szepeshazi** [comment]
@alan-knight I don't think this was properly merged and published. Using 0.17.7, invoking the `dart-files` option gives me the error message:
```
Unhandled exception:
FormatException: Could not find an option named "dart-files".
```
Also, the relevant code is missing both in `master` and in `0.17.6`.

**Comment by alan-knight** [comment]
Indeed. In the process of merging it now, although it needs a bit of work to be exercised within the test setup.

**Comment by liudonghua123** [comment]
I tried to add glob path parser support for this lib. see https://github.com/dart-lang/intl_translation/pull/92.
