### ISSUE TITLE
VS Code Plugin

### ISSUE THREAD

**Issue by amreniouinnovent** [dart-lang/intl_translation#68]
I have a suggestion for adding a VS Code plugin to easily edit the arb files for several languages in a better visual UI other than the json file.
Same like what is exist in Android Studio translation view.
https://developer.android.com/studio/write/translations-editor

![image](https://user-images.githubusercontent.com/52191652/60662000-41da6880-9e6c-11e9-9b81-7f72888aacfc.png)

**Comment by alan-knight** [comment]
That could be interesting. But I think there are a lot of existing translation tools out there, and mostly they are optimized for non-programmers, but rather for translators. And not for ARB files. I think we more likely would want to emit a different format (e.g. XLIFF) and use the existing tools.
