### ISSUE TITLE
Enum translation case sensitivity

### ISSUE THREAD

**Issue by ened** [dart-lang/intl_translation#69]
My current workflow is to setup enum translations in our Localization objects like so:

```
  String uploadStepTitle(UploadStep step) {
    return Intl.select(
      step,
      {
        UploadStep.review: 'Review',
        UploadStep.preparing: 'Preparing',
        UploadStep.uploading: 'Upload in Progress',
        UploadStep.uploadComplete: 'Upload Complete',
        UploadStep.uploadFailed: 'Upload Failed',
        'other': 'Upload',
      },
      name: 'uploadStepTitle',
      args: [step],
    );
  }
```

This will create ARB files which contain this:
```
  "uploadStepTitle": "{step,select, review{Review}preparing{Preparing}uploading{Upload in Progress}uploadComplete{Upload Complete}uploadFailed{Upload Failed}other{Upload}}",
  "@uploadStepTitle": {
    "type": "text",
    "placeholders": {
      "step": {}
    }
  },
```

When I bring the ARB file to a translation tool like the Google Translators toolkit, I will get the file back like this:

```
  "uploadStepTitle": "{step, select, review {Revue} preparing {Préparation} uploading {Téléchargement en cours} uploadcomplete {Téléchargement complet} uploadfailed {Échec du téléchargement} other {Télécharger}}",
  "@uploadStepTitle": {
    "type": "text",
    "placeholders": {
      "step": {}
    }
  },
```

You can see how the case has been changed to all lower case.

Now, the dart file generated through this package will read this way:

```
  static m48(step) => "${Intl.select(step, {'review': 'Revue', 'preparing': 'Préparation', 'uploading': 'Téléchargement en cours', 'uploadcomplete': 'Téléchargement complet', 'uploadfailed': 'Échec du téléchargement', 'other': 'Télécharger', })}";
```

Because of this, the French translation fails. My code tries to resolve the camelCased version of an enumeration value but only the lowercased version is translated & available.

I think the solution could be to standardize the any generated output to upper or lowercase.

Or, am I missing a configuration flag somewhere?

**Comment by alan-knight** [comment]
That is one solution, but you'd also need to do the case conversion on the arguments at runtime. That's why the current tests fail. I wasn't aware that the translation toolkit did that, and I don't think it's standard, so I'm a little reluctant to enforce that. An alternative approach would be when reading ARB files we match the translated to the original case-insensitively.

**Comment by ened** [comment]
@alan-knight ok. Is anyone working on this at the moment or is it up for grabs?

**Comment by alan-knight** [comment]
No one is working on it, by all means grab it

**Comment by creativecreatorormaybenot** [comment]
@alan-knight The Google Translator Toolkit definitely does this for all cases.

My solution is simply to call `toLowerCase` in every select message:

```dart
Intl.select(
  step.toString().toLowerCase(),
  ...
```

Considering https://github.com/dart-lang/intl_translation/issues/74#issue-494487688, I think that we might want to wait and see what other systems do. If other tools are case sensitive, i.e. keep it, this issue would be resolved.

**Comment by mosuem** [comment]
Closing in favor of #183 .
