### ISSUE TITLE
Support additional file format(s)

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [dart-lang/intl_translation#74]
It has just been [announced that Google Translator Toolkit is shutting down](https://support.google.com/translatortoolkit/answer/9462068) and that relatively soon, in 3 months (December 4, 2019).

I was not able to find software that allows to use `.arb` files. What are the plans for this plugin?

**Comment by alan-knight** [comment]
I think the correct answer is to add support for a more commonly used format. I have no strong opinion about formats, so if anyone wants to make suggestions that would be good. The format support is very pluggable, so it shouldn't be at all difficult to add. There is #52 which wants to make it possible to add support for different formats outside of the package itself, which is good, but I haven't done anything about it. Other than that, the biggest issue is if a format can support the full semantics easily. The other nice thing about Google Translator Toolkit was that it had some capability of automatic translation which makes it easy for testing or getting started.

**Comment by maszhin** [comment]
Yeah. With Google Translator Toolkit we (my company) got almost perfect cross-platform flow (Angular + Vue + Flutter).

I added question on stackoverflow: https://stackoverflow.com/questions/57972593/what-online-tool-do-you-use-to-automate-translation-of-arb-files

**Comment by creativecreatorormaybenot** [comment]
@alan-knight Do you think https://github.com/dart-lang/intl/issues/230#issuecomment-533705082 helps?

**Comment by alan-knight** [comment]
Yes, that definitely helps. I think it would be better if we could emit other format(s) directly, but the availability of a converter is very helpful and is an immediate solution. I don't have a sense of how widely "Hierarchical JSON" is supported.

**Comment by goranluledzija** [comment]
[Localizely](https://localizely.com/) supports ARB files.

We also published VS Code extension for simplified localization with ARB files: [Flutter Intl](https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl).
Android Studio plugin is also in the plan.

I hope this helps.

**Comment by shaxxx** [comment]
Localizely is 60$ per month. Thats a rip off IMHO.
Flutter intl. VS code plugin is developer tool,  aimed to help you create boilerplate once you got localizations ready. It's not gonna help during translation process.
Building tool to support arb files translations is not rocket science, but this is something Dart/Angular/Flutter team has to think about.

**Comment by goranluledzija** [comment]
There is a Free plan for Localizely as well, in case you don't need features from paid plans.

I mentioned Flutter Intl plugin due to title about file formats, but @shaxxx you are right, the main topic seems to be translation tools/platforms.

**Comment by jamesblasco** [comment]
The last few days I have been playing on creating a tool for editing arb files and compile it to intl dart files online

https://github.com/jamesblasco/arb_editor

If you have any feedback, I would love to hear it before working on make it stable and usable

**Comment by ChiefWiggum** [comment]
[BabelEdit ](https://www.codeandweb.com/babeledit) has added support for arb files, works like a charm and doesn't cost a fortune.

**Comment by jpc-ae** [comment]
Just to add that Crowdin also has support for arb now (https://support.crowdin.com/supported-formats/). It might be worth adding android xml as a format at least though, recognising that it has a limitation when it comes to genders.

**Comment by fkirc** [comment]
Since "Google Translator Toolkit" has been killed, I wrote the new tool `attranslate`: https://github.com/fkirc/attranslate
You can give `attranslate` a try if this is still an issue for you.
`attranslate` supports both JSON-files and ARB-files.

To be honest, I don't think that going from ARB back to JSON is a good path for the future.
JSON is a very crude translation-format that doesn't have a good support for basic features like comments or annotations.
Therefore, I think it's better to write new tools like `attranslate` instead of going back to over-primitive formats like JSON.

**Comment by mosuem** [comment]
Closing this in favor of the [package:intl issue](https://github.com/dart-lang/intl/issues/230).
