### ISSUE TITLE
Invalid typedef for MessageIfAbsent in generated code - static error

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/intl_translation#78]
Generated code with `v.0.17.6` for a project. The output contains a line like so:

```dart
typedef String MessageIfAbsent(String message_str, List<dynamic> args);
```

This triggers an error that `MessageLookup.lookupMessage` is an invalid override in the generated code. 
Rolling back to `0.17.5` fixed this.

Seems like that Intl 0.16.0 still defines the typedef with incompatible signature: https://github.com/dart-lang/intl/blob/0.16.0/lib/src/intl_helpers.dart#L14

**Comment by daniel-v** [comment]
@mosuem might I ask why this issue has been closed?

**Comment by mosuem** [comment]
As the corresponding issue in dart-lang was closed as fixed, I assumed this was the case for this issue as well - if it is not, I am happy to reopen.
