### ISSUE TITLE
FileSystemException: Cannot open file, path = 'lib/i18n/intl_messages.arb'

### ISSUE THREAD

**Issue by dbacinski** [dart-lang/intl_translation#8]
When running `intl_translation:extract_to_arb` I am getting an error `FileSystemException: Cannot open file`

```Dariuszs-MacBook-Pro:wms-flutter dariuszbacinski$ pub run intl_translation:extract_to_arb --output-dir=lib/i18n lib/strings.dart 
Unhandled exception:
FileSystemException: Cannot open file, path = 'lib/i18n/intl_messages.arb' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:599)
#1      _File.openSync (dart:io/file_impl.dart:454)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:568)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:592)
#4      main (http://localhost:57084/extract_to_arb.dart:63:8)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```
I thought that this script is suppose to create *.arb files...

This is a content of `lib/strings.dart`:
```
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

class Strings extends LocaleQueryData {
  static Strings of(BuildContext context) {
    return LocaleQuery.of(context);
  }

  static final Strings _singleton = new Strings();

  factory Strings() {
    return _singleton;
  }

  String signInButton() =>
      Intl.message(
        'Continue to Space OS',
        name: "signInButton",
        args: [],
      );
}
```

**Comment by dbacinski** [comment]
Target directory must exist, after creating `i18n` directory script has run successfully.

It is repeated to this issue: https://github.com/dart-lang/sdk/issues/27771

Maybe script can check if directory does not exists and then create it.

**Comment by deborah-ufw** [comment]
I also am having this issue. The directory exists.

**Comment by alan-knight** [comment]
Can you be more specific about the error you're getting.

**Comment by deborah-ufw** [comment]
"FileSystemException: Cannot open file, path = 'lib/i18n/intl_messages.arb' (OS Error: No such file or directory, errno = 2)"

It seems like it wants the file to be already there. I had a lot of difficulty with the documentation for translations and did finally get the scripts to work, but why they didn't work was very unclear.

**Comment by alan-knight** [comment]
From which program? For creating the ARB it shouldn't care if the file exists or not. To generate Dart code from the ARB it obviously needs the ARB to exist. And in either case it needs the directory. Maybe it was having a problem with the relative path and not finding the directory?

**Comment by deborah-ufw** [comment]
The script, as I understood the documentation, was supposed to _generate_ intl_messages.arb.
The directory did exist in the proper location relative to the project root.

**Comment by alan-knight** [comment]
Was the script being run from the project root? It only matters if it exists relative to the current program location.

**Comment by deborah-ufw** [comment]
Yes. The documentation says to run it from the project root. 
The documentation is out of date, I had already corrected this from "I10n" to "i18n", which is the name of the directory in the project.

"With the app’s root directory as the current directory, generate l10n/intl_messages.arb from lib/main.dart: ..."

https://flutter.io/tutorials/internationalization/

**Comment by ramah** [comment]
Hi @deborah-ufw  
just create the folder i10n in the folder lib

**Comment by mathieujobin** [comment]
there is no such thing as i10n, its a typo
i18n means internationalization
l10n means localization

i10n would mean internation

**Comment by liudonghua123** [comment]
I tried to add glob path parser support for this lib. see https://github.com/dart-lang/intl_translation/pull/92.
