### ISSUE TITLE
intl_translation:extract_to_arb - error is thrown when Intl.select() is used

### ISSUE THREAD

**Issue by supermuka** [dart-lang/intl_translation#81]
When Intl.select() is used an error is thrown.

**code:**
```
  String groupTypeName(String name) => Intl.select(name, {
        'GroupType.company': 'Company',
        'GroupType.businessUnit': 'Business Unit',
        'GroupType.department': 'Department',
        'GroupType.team': 'Team',
        'other': 'Not Defined'},
      name: "GroupDetailComponent_groupTypeName",
      args: [name],
      // locale: "en",
      desc: "Group type labels"
  );
```
**command:**
`pub run intl_translation:extract_to_arb --output-dir=lib/messages/i18n lib/src/group/group_detail_component.dart`

**error:**
> Error IntlMessageExtractionException: Invalid select keyword: 'GroupType.company', must match '[a-zA-Z][a-zA-Z0-9_-]*'
> Processing <Intl.select(name, {'GroupType.company' : 'Company', 'GroupType.businessUnit' : 'Business Unit', 'GroupType.department' : 'Department', 'GroupType.team' : 'Team', 'other' : 'Not Defined'}, name: "GroupDetailComponent_groupTypeName", args: [name], desc: "Gro
> up type labels")>    from lib/src/group/group_detail_component.dart    line: 293, column: 40
> Skipping invalid Intl.message invocation
>     <Intl.select(name, {'GroupType.company' : 'Company', 'GroupType.businessUnit' : 'Business Unit', 'GroupType.department' : 'Department', 'GroupType.team' : 'Team', 'other' : 'Not Defined'}, name: "GroupDetailComponent_groupTypeName", args: [name], desc: "Group type
>  labels")>
>     reason: Unexpected exception: NoSuchMethodError: The setter 'mainArgument=' was called on null.
> Receiver: null
> Tried calling: mainArgument="name", #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
> #1      PluralAndGenderVisitor.messageFromMethodInvocation (package:intl_translation/extract_messages.dart:629:15)
> #2      PluralAndGenderVisitor.visitMethodInvocation (package:intl_translation/extract_messages.dart:559:16)
> #3      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7233:49)
> #4      MessageFindingVisitor.messageFromDirectPluralOrGenderCall.extractFromPluralOrGender (package:intl_translation/extract_messages.dart:442:12)

**Comment by alan-knight** [comment]
From the first line
    must match '[a-zA-Z][a-zA-Z0-9_-]'
No periods.
