### ISSUE TITLE
Incompatible with latest version of Analyzer

### ISSUE THREAD

**Issue by supermuka** [dart-lang/intl_translation#83]
The recent versions of the `intl_translation` package isn't compatible with the latest version of the Analyzer package `0.39.2+1`.

`pub get update` shows:

Because intl_translation >=0.17.6 depends on analyzer >=0.36.0 <0.39.0 and auge_server depends on analyzer ^0.39.2+1, intl_translation >=0.17.6 is forbidden.
So, because auge_server depends on intl_translation ^0.17.7, version solving failed.

Dart SDK Version (dart --version)
2.7
intl_translation Version
0.17.7
Whether you are using Windows, macOS, or Linux
Windows
Whether you are using Chrome, Safari, Firefox, Edge
Chrome

**Comment by boskokg** [comment]
Can someone fix this please?

**Comment by alan-knight** [comment]
Published a new version.
