### ISSUE TITLE
Refactor to use dart:io as less as posible

### ISSUE THREAD

**Issue by jamesblasco** [dart-lang/intl_translation#84]
Hello, 

I am building a tool to edit arb files online and generate the intl translation on web. https://github.com/jamesblasco/arb_editor

While I can use almost everything from this package, I had to do some changes for supporting web as the dart:io package is needed in
https://github.com/dart-lang/intl_translation/blob/master/lib/generate_localized.dart
https://github.com/dart-lang/intl_translation/blob/master/bin/generate_from_arb.dart

My proposal is to refactor `generateIndividualMessageFile` in [generate_localized.dart](https://github.com/dart-lang/intl_translation/blob/master/lib/generate_localized.dart) to return the output.toString() and create the message file in [here](https://github.com/dart-lang/intl_translation/blob/e24b59d35a643c6b1060d02dcaa9e223fcad6050/bin/generate_from_arb.dart#L178)

And extract from [generate_localized.dart](https://github.com/dart-lang/intl_translation/blob/master/lib/generate_localized.dart) all the logic that doesn't have to do with writing and reading files in a separate class. 

Create a function that given the files in a map <fileName:String, fileContent:String> returns another map with the new files.
So dart:io would be only needed in generate_from_arb.dart

**Comment by jamesblasco** [comment]
If you think it could be a good approach I would be happy to help with a pull request

**Comment by alan-knight** [comment]
Thanks. Yes, that seems like a good idea to me.

**Comment by jamesblasco** [comment]
Fixed in #106
