### ISSUE TITLE
intl_translation:extract_to_arb not updating file (with new  / modified strings)

### ISSUE THREAD

**Issue by ricard-v** [dart-lang/intl_translation#87]
Hello !

First of all, I am fairly new at Flutter development so I might have gotten things wrong.

Second, thanks for this awesome plugin. For example, providing a `desc` field provides great help for translators.

Now, onto my issue.

1. In my app, I want to localize all my Strings and for that I have followed the official doc [here](https://flutter.dev/docs/development/accessibility-and-localization/internationalization) and the example [here](https://github.com/flutter/website/tree/master/examples/internationalization/intl_example).
2. I managed to generate my first `intl_messages.arb` using `intl_translation:extract_to_arb` which now contains all my current strings as defined in my `AppLocalizations` class.
3. then I cloned `intl_messages.arb` into `int_fr.arb` (_`fr` being my default locale_)
4. I declined for other supported locales: `int_de.arb`  and `int_it.arb` 
5. Finally I used `intl_translation:generate_from_arb`

And it works.

After a while, I decided to modify some strings and added some. Then I executed both commands `intl_translation:extract_to_arb` and `intl_translation:generate_from_arb` expecting it would update the files accordingly.

It did not ! Not only the `intl_messages.arb` has been modified since its creation, but all others `.arb` files have been modified !

After some testing, I even noticed that a single manual modification in `intl_messages.arb` will cause the same issue. Even stranger, the moment I cloned it into `int_fr.arb`, the issue appeared.

**What am I doing wrong ?** How am I supposed to update my translations as I am going forward in the project development ?

What if the translations had started while the app is being developed and new strings are added ? Would it overwrite the work done by the translators ?

**Comment by mosuem** [comment]
I am a bit confused - is this about the `package:intl_translation` workflow, using `intl_translation:extract_to_arb` and `intl_translation:generate_from_arb`, or about the Flutter workflow you linked (or has the link content changed since then?)?

Please reopen with more details, if this is still an issue.
