### ISSUE TITLE
Make parameters named instead of positional

### ISSUE THREAD

**Issue by MarcelGarus** [dart-lang/intl_translation#91]
`context.s.file_uploadProgressSnackBarContent(1, file.name, 0)` is not descriptive, but this is:
```dart
context.s.file_uploadProgressSnackBarContent(
  fileName: file.name,
  totalNumberOfFiles: 1,
  currentIndex: 0,
)
```

That's why I argue for making parameters named and `@required` instead of positional by default.

**Comment by mosuem** [comment]
I don't understand - where is your example coming from?
