### ISSUE TITLE
Upgrade deps on xml and petitparser

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/intl_translation#93]
Currently this package is not compatible with xml `3.7.0`, likely because it's not compatible with petitparser `>3.0.0`:

```
And because intl_translation >=0.17.2 depends on petitparser >=1.1.3 <3.0.0 and xml >=3.7.0 depends on petitparser ^3.0.0, xml >=3.7.0 is incompatible with intl_translation.
```

Can we roll this package to latest xml and petitparser?

While we are at it, probably bump the minimum Dart SDK to 2.7.0 (as several latest deps require that).

**Comment by mit-mit** [comment]
This is currently blocking all flutter apps from latest xml, see https://github.com/flutter/flutter/pull/53467#issuecomment-605437771

**Comment by mit-mit** [comment]
cc @alan-knight

**Comment by mit-mit** [comment]
cc @davidmorgan

**Comment by davidmorgan** [comment]
Thanks. How urgent is this?

`intl_translation` is developed in google3 first, and it looks like `petit_parser` is on `2.3.0` there, so I think the first job is to look at updating that. Doesn't look too bad though, just a small number of users.

Filed b/152760228

**Comment by mit-mit** [comment]
This is pretty high severity; we're holding back all Flutter apps from getting latest versions of those two packages.

Thus, in terms of urgency, I'd like to see this fixed no later than in a few weeks. Is that possible? That is extra upside if fixed sooner, as the fix then has a good chance of making it into the next stable build.

**Comment by davidmorgan** [comment]
Thanks. Likely doable, work happening on b/152760228

**Comment by davidmorgan** [comment]
Published--please let me know if you hit any issues.

**Comment by mit-mit** [comment]
Looks great, thanks! https://github.com/flutter/flutter/pull/54181
